# Generated by Django 4.0.5 on 2022-06-06 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='categoy',
            field=models.CharField(choices=[('Recusos Humanos', 'Recusos Humanos'), ('Contabilidad', 'Contabilidad'), ('Gerencia', 'Gerencia')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
