# Generated by Django 4.0.5 on 2022-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_ticket_categoy_alter_ticket_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='categoy',
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='Gerencia', max_length=50),
            preserve_default=False,
        ),
    ]
