# Generated by Django 4.0.5 on 2022-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_remove_ticket_categoy_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nuevo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Recusos Humanos', 'Recusos Humanos'), ('Contabilidad', 'Contabilidad'), ('Gerencia', 'Gerencia')], max_length=50),
        ),
    ]
