# Generated by Django 4.0.5 on 2022-06-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_ticket_nuevo_id_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='nuevo_id',
        ),
    ]
