# Generated by Django 4.0.5 on 2022-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_remove_ticket_nuevo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Incidente', 'Incidente'), ('Requerimiento', 'Requerimiento'), ('Logistica', 'Logistica')], default='Abierto', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Incidente', 'Incidente'), ('Requerimiento', 'Requerimiento'), ('Logistica', 'Logistica')], max_length=50),
        ),
    ]
