# Generated by Django 4.0.5 on 2022-06-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_ticket_state_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='timeclosing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
