# Generated by Django 4.0.5 on 2022-06-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_ticket_state_alter_ticket_timeclosing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
